
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.4 EDK_LS4.68
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xlltemac.h"

/*
* The configuration table for devices
*/

XLlTemac_Config XLlTemac_ConfigTable[] =
{
	{
		XPAR_LLTEMAC_0_DEVICE_ID,
		XPAR_LLTEMAC_0_BASEADDR,
		XPAR_LLTEMAC_0_TXCSUM,
		XPAR_LLTEMAC_0_RXCSUM,
		XPAR_LLTEMAC_0_PHY_TYPE,
		XPAR_LLTEMAC_0_TXVLAN_TRAN,
		XPAR_LLTEMAC_0_RXVLAN_TRAN,
		XPAR_LLTEMAC_0_TXVLAN_TAG,
		XPAR_LLTEMAC_0_RXVLAN_TAG,
		XPAR_LLTEMAC_0_TXVLAN_STRP,
		XPAR_LLTEMAC_0_RXVLAN_STRP,
		XPAR_LLTEMAC_0_MCAST_EXTEND,
		XPAR_LLTEMAC_0_INTR,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_TYPE,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_BASEADDR,
		0xFF,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_DMARX_INTR,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_DMATX_INTR
	}
};

