
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.4 EDK_LS4.68
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xwdttb.h"

/*
* The configuration table for devices
*/

XWdtTb_Config XWdtTb_ConfigTable[] =
{
	{
		XPAR_XPS_TIMEBASE_WDT_0_DEVICE_ID,
		XPAR_XPS_TIMEBASE_WDT_0_BASEADDR
	}
};


