
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.4 EDK_LS4.68
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_IIC_EEPROM_DEVICE_ID,
		XPAR_IIC_EEPROM_BASEADDR,
		XPAR_IIC_EEPROM_TEN_BIT_ADR,
		XPAR_IIC_EEPROM_GPO_WIDTH
	}
};


