
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.4 EDK_LS4.68
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#define MICROBLAZE_PVR_NONE
